// <auto-generated />
using GameDevsConnect.Backend.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDevsConnect.Backend.Shared.Migrations
{
    [DbContext(typeof(GDCDbContext))]
    partial class GDCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.RequestLike", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owner_id");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("request_id");

                    b.ToTable("Request_Like", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.CommentModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("created");

                    b.Property<byte?>("Deleted")
                        .HasColumnType("tinyint")
                        .HasColumnName("deleted");

                    b.Property<string>("FileId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("file_id");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owner_id");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("request_id");

                    b.HasKey("Id")
                        .HasName("PK__Comments__3213E83F66D90817");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.FileModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owner_id");

                    b.Property<int?>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("PK__Files__3213E83FF08B3AF0");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.NotificationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("created");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owner_id");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("request_id");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit")
                        .HasColumnName("seen");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3213E83FFA33E195");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.ProfileModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("DiscordUrl")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("discord_url");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("email");

                    b.Property<byte?>("ShowDiscord")
                        .HasColumnType("tinyint")
                        .HasColumnName("show_discord");

                    b.Property<byte?>("ShowEmail")
                        .HasColumnType("tinyint")
                        .HasColumnName("show_email");

                    b.Property<byte?>("ShowWebsite")
                        .HasColumnType("tinyint")
                        .HasColumnName("show_website");

                    b.Property<byte?>("ShowX")
                        .HasColumnType("tinyint")
                        .HasColumnName("show_x");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("user_id");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("website_url");

                    b.Property<string>("XUrl")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("x_url");

                    b.HasKey("Id")
                        .HasName("PK__Profiles__3213E83F90589B08");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.ProjectModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Projects__3213E83F52B40C40");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.ProjectTeam", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("project_id");

                    b.Property<string>("TeamMemberId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("team_member_id");

                    b.ToTable("Project_Team", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.RequestModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("FileId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("file_id");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("owner_id");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Requests__3213E83F7C3B1A3E");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.RequestTag", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("request_id");

                    b.Property<int?>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.ToTable("Request_Tag", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.TagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("PK__Tags__3213E83FFFD2E1F7");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("GameDevsConnect.Backend.Shared.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("Accounttype")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("accounttype");

                    b.Property<string>("Avatar")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("avatar");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83F1FAE596D");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
