version: "3.8"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql.server
    hostname: mssql
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1401:1433"

  gamedevsconnect.backend.api.auth:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapiauth
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Auth/Dockerfile
    container_name: api.auth
    ports:
        - "7001:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7001"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.azure:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapiazure
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Azure/Dockerfile
    container_name: api.azure
    ports:
        - "7002:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7002"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.comment:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapicomment
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Comment/Dockerfile
    container_name: api.comment
    ports:
        - "7003:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7003"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.file:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapifile
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.File/Dockerfile
    container_name: api.file
    ports:
        - "7004:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7004"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.notification:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapinotification
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Notification/Dockerfile
    container_name: api.notification
    ports:
        - "7005:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7005"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.project:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapiproject
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Project/Dockerfile
    container_name: api.project
    ports:
        - "7006:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7006"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.request:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapirequest
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Request/Dockerfile
    container_name: api.request
    ports:
        - "7007:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7007"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.tag:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapitag
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Tag/Dockerfile
    container_name: api.tag
    ports:
        - "7008:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7008"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.user:
    image: ${DOCKER_REGISTRY-}gamedevsconnectbackendapiuser
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.User/Dockerfile
    container_name: api.user
    ports:
        - "7009:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7009"
    depends_on:
     - mssql
