services:
  mssql:
    image: "benexdrake012/gamedevsconnectdb"
    container_name: backend.sql.server
    hostname: mssql
    environment:
      - MSSQL_SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1401:1433"

  gamedevsconnect.backend.api.gateway:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapigateway
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Gateway/Dockerfile
    container_name: backend.api.gateway
    ports:
        - "7001:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7001"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.azure:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapiazure
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Azure/Dockerfile
    container_name: backend.api.azure
    ports:
        - "7002:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7002"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.comment:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapicomment
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Comment/Dockerfile
    container_name: backend.api.comment
    ports:
        - "7003:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7003"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.file:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapifile
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.File/Dockerfile
    container_name: backend.api.file
    ports:
        - "7004:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7004"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.notification:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapinotification
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Notification/Dockerfile
    container_name: backend.api.notification
    ports:
        - "7005:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7005"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.project:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapiproject
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Project/Dockerfile
    container_name: backend.api.project
    ports:
        - "7006:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7006"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.profile:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapiprofile
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Profile/Dockerfile
    container_name: backend.api.profile
    ports:
        - "7007:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7007"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.request:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapirequest
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Request/Dockerfile
    container_name: backend.api.request
    ports:
        - "7008:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7008"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.tag:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapitag
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.Tag/Dockerfile
    container_name: backend.api.tag
    ports:
        - "7009:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7009"
    depends_on:
     - mssql

  gamedevsconnect.backend.api.user:
    image: ${DOCKER_REGISTRY-}benexdrake012/gamedevsconnectbackendapiuser
    build:
      context: .
      dockerfile: GameDevsConnect.Backend.API.User/Dockerfile
    container_name: backend.api.user
    ports:
        - "7010:8080"
    environment:
        - "ASPNETCORE_URL=http://*:7010"
    depends_on:
     - mssql
