apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-comment
  namespace: gamedevsconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-comment
  template:
    metadata:
      labels:
        app: api-comment
    spec:
      containers:
        - name: api-comment
          image: benexdrake012/gamedevsconnect_backend_api_comment
          ports:
            - containerPort: 8080