apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gamedevsconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: benexdrake012/gamedevsconnect_frontend
          ports:
            - containerPort: 8080