apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-request
  namespace: gamedevsconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-request
  template:
    metadata:
      labels:
        app: api-request
    spec:
      containers:
        - name: api-request
          image: benexdrake012/gamedevsconnect_backend_api_request
          ports:
            - containerPort: 8080