apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  namespace: gamedevsconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: api-user
          image: benexdrake012/gamedevsconnect_backend_api_user
          ports:
            - containerPort: 8080