apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-file
  namespace: gamedevsconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-file
  template:
    metadata:
      labels:
        app: api-file
    spec:
      containers:
        - name: api-file
          image: benexdrake012/gamedevsconnect_backend_api_file
          ports:
            - containerPort: 8080