apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-notification
  namespace: gamedevsconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-notification
  template:
    metadata:
      labels:
        app: api-notification
    spec:
      containers:
        - name: api-notification
          image: benexdrake012/gamedevsconnect_backend_api_notification
          ports:
            - containerPort: 8080