apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-azure
  namespace: gamedevsconnect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-azure
  template:
    metadata:
      labels:
        app: api-azure
    spec:
      containers:
        - name: api-azure
          image: benexdrake012/gamedevsconnect_backend_api_azure
          ports:
            - containerPort: 8080