global using GameDevsConnect.Backend.API.Post.Contract.Request;
global using GameDevsConnect.Backend.API.Post.Contract.Response;
global using GameDevsConnect.Backend.API.Configuration.Data;
global using GameDevsConnect.Backend.API.Configuration.DTOs;
global using GameDevsConnect.Backend.API.Configuration.Responses;
global using Microsoft.EntityFrameworkCore;
global using Serilog;
global using FluentValidation;
global using GameDevsConnect.Backend.API.Post.Application.Validators;